config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'
  get '/contact' => 'welcome#contact', :as => :contact
  post '/email_contact' => 'welcome#email_contact', :as => :email_contact
  get '/participents' => 'welcome#participents', :as => :participents
  get '/result' => 'welcome#result', :as => :result
  get '/shedule' => 'welcome#shedule', :as => :shedule
  get '/today_match' => 'welcome#today_match', :as => :today_match
  get '/organizer' => 'welcome#organizer', :as => :organizer
  get '/match_pdf' => 'welcome#match_pdf', :as => :match_pdf
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :users, :only => [:create]
  resources :sessions
  resources :contests
  resources :matches
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/contest.rb
class Contest < ActiveRecord::Base
end

app/models/match.rb
class Match < ActiveRecord::Base
  mount_uploader :image1, ImageUploader
  mount_uploader :image2, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all.reverse
  end

  def new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to comments_path
    else
      render 'new'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_name)
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def index
  end
  def new
  end

  def create
    @contest = Contest.new(contest_params)
    if @contest.save
      respond_to  do |format|
        format.html {redirect_to result_path}
      end
    else
      respond_to do |format|
        format.html {render 'new'}
      end
    end
  end

  def edit
    @contest = Contest.find(params[:id])
  end

  def update
       @contest = Contest.find(params[:id])
       if @contest.update(contest_params)
        redirect_to result_path
       else
        render 'edit'
       end
  end

  def destroy
    @contest = Contest.find(params[:id])
    @contest.destroy
    redirect_to result_path
  end

  private

  def contest_params
    params.require(:contest).permit(:match_number, :player_first, :player_second, :match_point)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
  end

  def new
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      respond_to  do |format|
        format.html {redirect_to today_match_path}
      end
    else
      respond_to do |format|
        format.html {render 'new'}
      end
    end
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
       @match = Match.find(params[:id])
       if @match.update(match_params)
        redirect_to today_match_path
       else
        render 'edit'
       end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to today_match_path
  end

  private

  def match_params
    params.require(:match).permit(:player_first, :image1, :player_second, :image2, :remote_image_url)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  
 private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  def email_contact
    @name = params[:contact][:name]
    @email = params[:contact][:email]
    @phone = params[:contact][:phone]
    @message = params[:contact][:message]
    @to_email = "plingaiah@qwinixtech.com"
      ContactMailer.contact_email(@email, @to_email, @name, @phone, @message).deliver
      # flash[:notice] = "The Contact Information has been sent"
      redirect_to root_url
  end

  def participents
  end

  def result
    @contests = Contest.all.reverse
  end

  def shedule
  end

  def today_match
    @matches = Match.all
  end

  def organizer
  end

  def match_pdf
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<div class="section-modal contact">
    <div class="modal-content">
        <div class="container">
        <h2 class="match-heading">Comment Box</h2>
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'qwinixpingpongherokuappcom';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'qwinixpingpongherokuappcom';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
</div>
</div>
</div>

app/views/contests/edit.html.erb
<%= form_for :contest,:url=>contest_path,method: "put" do |f| %>
  <p>
    <%= f.label :match_number %><br>
    <%= f.text_field :match_number %>
  </p>
 
  <p>
    <%= f.label :player_first %><br>
    <%= f.text_field :player_first %>
  </p>

  <p>
    <%= f.label :player_second %><br>
    <%= f.text_field :player_second %>
  </p>

  <p>
    <%= f.label :match_point %><br>
    <%= f.text_field :match_point %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/contests/index.html.erb
<h1>Contests#index</h1>
<p>Find me in app/views/contests/index.html.erb</p>

app/views/contests/new.html.erb
<%= form_for :contest,:url=>contests_path,method: "post" do |f| %>
  <p>
    <%= f.label :match_number %><br>
    <%= f.text_field :match_number %>
  </p>
 
  <p>
    <%= f.label :player_first %><br>
    <%= f.text_field :player_first %>
  </p>

  <p>
    <%= f.label :player_second %><br>
    <%= f.text_field :player_second %>
  </p>

  <p>
    <%= f.label :match_point %><br>
    <%= f.text_field :match_point %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/matches/edit.html.erb
<%= form_for :match,:url=>match_path,method: "put" do |f| %>
  <p>
    <%= f.label :player_first %><br>
    <%= f.text_field :player_first %>
  </p>
 
  <p>
    <%= f.label :image1 %><br>
    <%= f.file_field :image1 %>
  </p>

  <p>
    <%= f.label :player_second %><br>
    <%= f.text_field :player_second %>
  </p>

  <p>
    <%= f.label :image2 %><br>
    <%= f.file_field :image2 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/matches/index.html.erb
<h1>Matches#index</h1>
<p>Find me in app/views/matches/index.html.erb</p>

app/views/matches/new.html.erb
<%= form_for :match,:url=>matches_path,method: "post" do |f| %>
  <p>
    <%= f.label :player_first %><br>
    <%= f.text_field :player_first %>
  </p>
 
  <p>
    <%= f.label :image1 %><br>
    <%= f.file_field :image1 %>
  </p>

  <p>
    <%= f.label :player_second %><br>
    <%= f.text_field :player_second %>
  </p>

  <p>
    <%= f.label :image2 %><br>
    <%= f.file_field :image2 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for :user,:url=>users_path,method: "post" do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/welcome/_second.html.erb
<h3 class="match-heading padding-slider">2nd Round</h3>

    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">VENKAT</div>
            <div class="col-sm-3">SAJITH</div>
            <div class="col-sm-2">17-08-2016 </div>
            <div class="col-sm-2">1.00 PM </div>
            <div class="col-sm-2">Match-13</div>
        </div>
    </div><br>
    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">PRAKASH</div>
            <div class="col-sm-3">VIJAY</div>
            <div class="col-sm-2">17-08-2016 </div>
            <div class="col-sm-2">1.20 PM </div>
            <div class="col-sm-2">Match-14</div>
        </div>
    </div><br>
    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">AKSHAY</div>
            <div class="col-sm-3">KEDAR</div>
            <div class="col-sm-2">17-08-2016 </div>
            <div class="col-sm-2">1.40 PM </div>
            <div class="col-sm-2">Match-15</div>
        </div>
    </div><br>
    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">UJWALA</div>
            <div class="col-sm-3">SUCHITRA</div>
            <div class="col-sm-2">17-08-2016 </div>
            <div class="col-sm-2">1.50 PM </div>
            <div class="col-sm-2">Match-16</div>
        </div>
    </div>
    <div class="journal-entry-devider"></div>
    <br>
    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">SHIMITH</div>
            <div class="col-sm-3">MATCH 10TH WINNER</div>
            <div class="col-sm-2">18-08-2016 </div>
            <div class="col-sm-2">1.00 PM </div>
            <div class="col-sm-2">Match-17</div>
        </div>
    </div><br>
    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">PRAVEEN</div>
            <div class="col-sm-3">MATCH 11TH WINNER</div>
            <div class="col-sm-2">18-08-2016 </div>
            <div class="col-sm-2">1.20 PM </div>
            <div class="col-sm-2">Match-18</div>
        </div>
    </div><br>
    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">RAVI SHANKAR</div>
            <div class="col-sm-3">MATCH 12TH WINNER</div>
            <div class="col-sm-2">18-08-2016 </div>
            <div class="col-sm-2">1.40 PM </div>
            <div class="col-sm-2">Match-19</div>
        </div>
    </div><br>
    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">SHARMILA</div>
            <div class="col-sm-3">APEKSHA</div>
            <div class="col-sm-2">18-08-2016 </div>
            <div class="col-sm-2">1.50 PM </div>
            <div class="col-sm-2">Match-20</div>
        </div>
    </div>
    <div class="journal-entry-devider"></div>
    <br>
    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">PRAKRUTHI</div>
            <div class="col-sm-3">DISHA</div>
            <div class="col-sm-2">19-08-2016 </div>
            <div class="col-sm-2">1.00 PM </div>
            <div class="col-sm-2">Match-21</div>
        </div>
    </div><br>
    <!-- <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">Shashi</div>
            <div class="col-sm-3">PRAKASH</div>
            <div class="col-sm-2">23-03-2015 </div>
            <div class="col-sm-2">4.45 PM </div>
            <div class="col-sm-2">Match-27</div>
        </div>
    </div><br>
    <div class="row message-box-high">
        <div class="col-sm-12">
            <div class="col-sm-3">Kiran</div>
            <div class="col-sm-3">Praveen</div>
            <div class="col-sm-2">23-03-2015 </div>
            <div class="col-sm-2">5.10 PM </div>
            <div class="col-sm-2">Match-28</div>
        </div>
    </div> -->

app/views/welcome/contact.html.erb
 <!-- Start Contact Section -->
        <div class="section-modal contact">
            <div class="modal-content">
                <!-- <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div> -->

                <div class="container">
                    <div class="row">
                        <div class="section-title text-center">
                            <h3 class="match-heading">Contact With Us</h3>
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-4">
                            <div class="footer-contact-info">
                                <h4>Contact Person</h4>
                                <ul>
                                    <li><strong>Name :</strong>Kedarnag</li>
                                    <li><strong>E-mail :</strong> ksatish@qwinix.io</li>
                                    <li><strong>Mobile :</strong> +919663002408</li>
                                    <li><strong>Skype name :</strong> kedarnag.m.s</li>
                                </ul>
                            </div>
                        </div>


                        <div class="col-md-4">
                            <div class="footer-contact-info">
                                <h4>Contact Person</h4>
                                <ul>
                                    <li><strong>Name :</strong>Praveen Menon</li>
                                    <li><strong>E-mail :</strong> pmenon@qwinix.io</li>
                                    <li><strong>Mobile :</strong> +919886204998</li>
                                    <li><strong>Skype name :</strong> praveenmenon_9</li>
                                </ul>
                            </div>
                        </div>

                        <!-- <div class="col-md-4">
                            <div class="footer-contact-info">
                                <h4>Contact Person</h4>
                                <ul>
                                    <li><strong>Name :</strong>Raghavendra K S</li>
                                    <li><strong>E-mail :</strong>rksanjeevarayappa@qwinixtech.com</li>
                                    <li><strong>Mobile :</strong> </li>
                                    <li><strong>Skype name :</strong> raghupcf</li>
                                </ul>
                            </div>
                        </div> -->

                    </div><!--/.row -->
                    <div class="row" style="padding-top: 80px;">
                        <div class="col-md-12">
                            <form name="sentMessage" id="contactForm" novalidate>
                            <%= form_tag email_contact_path, :id => 'contact_email_form', :class => 'new-contact-padding', :authenticity_token => true do %>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Your Name *" id="name" required data-validation-required-message="Please enter your name.">
                                            <p class="help-block text-danger"></p>
                                        </div>
                                        <div class="form-group">
                                            <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
                                            <p class="help-block text-danger"></p>
                                        </div>
                                        <div class="form-group">
                                            <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number.">
                                            <p class="help-block text-danger"></p>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <textarea class="form-control" placeholder="Your Message *" id="message" required data-validation-required-message="Please enter a message."></textarea>
                                            <p class="help-block text-danger"></p>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="col-lg-12 text-center">
                                        <div id="success"></div>
                                        <button type="submit" class="btn btn-primary">Send Message</button>
                                    </div>
                                </div>
                                <% end %>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <!-- End Contact Section -->

app/views/welcome/index.html.erb
    <head>

        <!-- Font Awesome CSS -->
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <!-- Bootstrap core CSS -->

        <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

    </head>
    
    <body>
        
        <!-- Start Logo Section -->
        <section id="logo-section" class="text-center">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo text-center">
                            <h1>Ping Pong</h1>
                            <span>It is Our Game</span>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Logo Section -->
        
        
        <!-- Start Main Body Section -->
        <div class="mainbody-section text-center">
            <div class="container">
                <div class="row">
                    
                    <div class="col-md-3">
                        
                        <div class="menu-item blue">
                            <a href="<%= shedule_path %>">
                                <i class="fa fa-cog"></i>
                                <p>Match Schedule</p>
                            </a>
                        </div>
                        
                        <div class="menu-item green">
                            <a href="<%= today_match_path %>">
                                <i class="fa fa-eye"></i>
                                <p>Winners</p>
                            </a>
                        </div>

                         <div class="menu-item color">
                            <a href="<%= result_path %>" data-toggle="modal">
                                <i class="fa fa-comment-o"></i>
                                <p>Results</p>
                            </a>
                        </div>

                        
                    </div>
                    
                    <div class="col-md-6 padding-slider">
                        
                        <!-- Start Carousel Section -->
                        <div class="home-slider">
                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="padding-bottom: 30px;">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                </ol>

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <img src="../assets/tb4.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="item">
                                        <img src="../assets/tb3.jpg" class="img-responsive" alt="">
                                    </div>
                                    <div class="item">
                                        <img src="../assets/tb1.jpg" class="img-responsive" alt="">
                                    </div>

                                </div>

                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="menu-item color responsive">
                                <a href="<%= comments_path %>" data-toggle="modal">
                                    <i class="fa fa-comments"></i>
                                    <p>Comments Box</p>
                                </a>
                            </div>
                        </div>
                        
                    </div>


                    
                    <div class="col-md-3">
                        
                        <div class="menu-item light-red">
                            <a href="<%= participents_path %>" data-toggle="modal">
                                <i class="fa fa-users"></i>
                                <p>Participants</p>
                            </a>
                        </div>
                        
                       <div class="menu-item color responsive">
                            <a href="<%= contact_path %>">
                                <i class="fa fa-phone"></i>
                                <p>Contact</p>
                            </a>
                        </div>
                        
                        <div class="menu-item color responsive">
                            <a href="<%= organizer_path %>">
                                <i class="fa fa-user"></i>
                                <p>Organizer</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Main Body Section -->
        
        <!-- Start Copyright Section -->
        <div class="copyright text-center">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div>Qwinix Ping Pong Tournament</div>
                        <div>
                            <% if current_user %>
                            <%= link_to "Log out", log_out_path %>
                            <% else %>
                            <%#= link_to "Sign up", new_user_path %>
                            <%= link_to "log in", new_session_path %>
                            <% end %>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- End Copyright Section -->
    </body>
    

app/views/welcome/match_pdf.html.erb
<div class="section-modal">
<div class="modal-content">
<div class="container">
<!-- <img src="../assets/qwinix tt championship.pdf" class="img-responsive" alt=""> -->
<embed src="../assets/Table_Tennis_Tournament 2016_17.pdf" width=1200px height=2100px>
</div>
</div>
</div>

app/views/welcome/organizer.html.erb
<div class="section-modal contact">
    <div class="modal-content">
        <div class="container">
        <h2 class="match-heading">Organizer</h2>
        <div class="col-md-3 col-sm-6 back-ground-color">
        	<div class="team-member">
        	<img src="../assets/team/qwinix_logo_small.png" class="img-responsive" alt="">
        	</div>
        </div>
        <div class="qwinix-adress">
        			<p>
        				Qwinix Technologies Pvt. Ltd.<br>
        				Special Plot No. 5, Horizon,<br>
        				HIEMA Convention Center Road,<br>
        				Hebbal Industrial Estate,<br>
        				Mysore – 570016<br>
        				Tel: +91 821 241 3535<br>
        				Email: info-india@qwinixtech.com<br>
        			</p>
        		</div>
        </div>
    </div>
</div>

app/views/welcome/today_match.html.erb
 <!-- Start Testimonial Section -->
        <div class="section-modal">
            <div class="modal-content">
                <!-- <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div> -->
                
                <% if current_user.present? %>
                <a href="<%= new_match_path %>">live update</a>
                <% end %>
                
                <div class="container">
                    <div class="row">
                        <div class="section-title text-center">
                            <h3>2015 Ping Pong Results</h3>
                            <p></p>
                        </div>
                    </div>

                    <% @matches.each do |match| %>
                    <div class="row">
                        
                        <div class="col-md-6">
                            <div class="testimonial">
                               <%= image_tag match.image1_url(:thumb) %>
                                <div class="speech">
                                <h2>Winner</h2>
                                    <h2><%= match.player_first%></h2>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="testimonial">
                                <%= image_tag match.image2_url(:thumb) %>
                                <div class="speech">
                                <h2>Runner</h2>
                                    <h2><%= match.player_second%></h2>
                                </div>
                            </div>
                        </div>

                        <% if current_user.present? %>
                                <a href="<%= edit_match_path(match) %>">edit</a>
                                <%= link_to "destroy", match_path(match), method: :delete, data: {confirm: 'Are u sure'} %>
                        <% end %>

                        <!-- <div class="col-md-6">
                            <div class="testimonial">
                                <img src="../assets/team/Prem.jpg" class="img-responsive" alt="...">
                                <div class="speech">
                                    <h2>Prem</h2>
                                </div>
                            </div>
                        </div> -->
                        
                        <!-- <div class="col-md-6">
                            <div class="testimonial">
                                <img src="../assets/team/Santosh.jpg" class="img-responsive" alt="...">
                                <div class="speech">
                                    <h2>Santosh</h2>
                                </div>
                            </div>
                        </div> -->
                        
                        <!-- <div class="col-md-6">
                            <div class="testimonial">
                                <img src="../assets/team/Prakash.jpg" class="img-responsive" alt="...">
                                <div class="speech">
                                    <h2>Prakash</h2>
                                </div>
                            </div>
                        </div> -->

                        <!-- <div class="col-md-6">
                            <div class="testimonial">
                                <img src="../assets/team/Anup.jpg" class="img-responsive" alt="...">
                                <div class="speech">
                                    <h2>Anup</h2>
                                </div>
                            </div>
                        </div> -->
                        
                        
                    </div><!--/.row -->
                    <% end %>
                    
                </div>
                
            </div>
        </div>
        <!-- End Testimonial Section -->